"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ](bold red)"
vicmd_symbol = "[î˜«](bold yellow)"

[aws]
symbol = "îŒ½  "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[buf]
symbol = "ï’ "

[c]
format = "[via](bold white) [$name $version ]($style)" 

[conda]
symbol = "ï„Œ "

[cmake]
format = "[via](bold white) [${symbol}(${version} )]($style)"

[cmd_duration]
format = "[took](bold white) [$duration]($style) "

[dart]
symbol = "î˜ "

[directory]
read_only = " ğŸ”’"

[docker_context]
symbol = "ïŒˆ "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[elixir]
symbol = "î‰µ "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[elm]
symbol = "î˜¬ "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[git_branch]
symbol = "ï˜ "
style  = "purple"
format = "[on](bold white) [$symbol]($style)[$branch ](bold $style)"

[golang]
symbol = "î˜§ "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[haskell]
symbol = "î· "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[hostname]
style  = "bold dimmed blue"
format = "[$hostname]($style) [in](bold white) "

[hg_branch]
symbol = "ï˜ "
format = "[on](bold white) [$symbol$branch]($style) "

[java]
symbol = "î‰– "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[julia]
symbol = "î˜¤ "
format = "[via](bold white) [${symbol}(${version} )]($style)"

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "
style  = "green"
format = "[via](bold white) [${symbol}]($style)[(${version} )](bold $style)"

[package]
symbol = "ï£– "
style  = "208"
format = "[is](bold white) [${symbol}]($style)[(${version} )](bold $style)"
disabled = true

[perl]
format = "[via](bold white) [${symbol}]($style)[(${version} )](bold $style)"

[python]
symbol = "î˜† "
style  = "yellow"
format = "[via](bold white) [${symbol}]($style)[(${version} )](bold $style)"

[rust]
symbol = "î¨ "
style  = "red"
format = "[via](bold white) [${symbol}]($style)[(${version} )](bold $style)"

[username]
format = "[$user]($style) [on](bold white) "
